
spring:
  jpa:
    database: postgresql
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    password: Sa123
    driver-class-name: org.postgresql.Driver
    username: postgres
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/ExcelSoft
  sql:
    init:
      mode: always
server:
  port: '8090'
